### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by zevaverbach** [lee-lindley/vim_plsql_syntax#2]
@lee-lindley thank you so much for sharing this repo; can you please point me in the right direction for installing these files into vim (in my case SpaceVim/neovim)?

**Comment by lee-lindley** [comment]
There is a section in README.md at the bottom titled "Installation". I do not know neovim. If it is based on core vim, it shouldn't vary too much from those instructions. You'll need to check the neovim documentation if you run into issues.
Good luck.
